version: 2.3.0
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
  - develop
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build:
  project: build.msbuild
  verbosity: normal
artifacts:
- path: build/package/**/*.nupkg
  name: NuGet Package
- path: build/package/**/*.zip
  name: Zip Archive
skip_commits:
  message: /\[nobuild\]/
deploy:
- provider: NuGet
  artifact: /.*\.nupkg/
  on:
    branch: develop